targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      drift_dev:
        options:
          databases:
            db: "lib/core/db/db.dart"
          schema_dir: "lib/core/db/schemas"
          store_date_time_values_as_text: true
      # protoc_builder:
      #   options:
      #     protobuf_version: "3.1.0"
      #     protoc_plugin_version: "21.1.2"
      #     root_dir: "assets/proto"
      #     proto_paths:
      #       - "assets/proto"
      #     out_dir: "lib/gen/proto"
      #     use_installed_protoc: true
      #     precompile_protoc_plugin: false
