import 'package:flutter/widgets.dart';

String windowsText(Locale locale, String key, {Map<String, String> params = const {}}) {
  final localeKey = switch (locale.toString()) {
    'zh_CN' => 'zh_CN',
    'zh_TW' => 'zh_TW',
    _ => 'en',
  };

  final value = _windowsLocalizedStrings[localeKey]?[key] ?? _windowsLocalizedStrings['en']![key] ?? key;
  return params.entries.fold<String>(value, (result, entry) => result.replaceAll('{${entry.key}}', entry.value));
}

String windowsCountryName(Locale locale, String chineseName) {
  final localeKey = switch (locale.toString()) {
    'zh_CN' => 'zh_CN',
    'zh_TW' => 'zh_TW',
    _ => 'en',
  };

  return _windowsCountryNames[localeKey]?[chineseName] ?? _windowsCountryNames['en']?[chineseName] ?? chineseName;
}

const _windowsLocalizedStrings = <String, Map<String, String>>{
  'en': {
    'splash.initializing': 'Initializing...',
    'splash.network': 'Checking network adapter...',
    'splash.sdk': 'Initializing SDK...',
    'splash.subtitle': 'VPN that always connects',
    'common.back': 'Back',
    'common.cancel': 'Cancel',
    'common.upload': 'Upload',
    'common.insert': 'Insert',
    'common.append': 'Append',
    'common.searchNext': 'Next',
    'common.searchPrevious': 'Previous',
    'common.error': 'Error',
    'common.copy': 'Copy',
    'common.idLabel': 'ID: {value}',
    'common.peopleUnit': 'people',
    'common.minutesUnit': 'minutes',
    'common.hoursUnit': 'hours',
    'home.title': 'Home',
    'home.welcomeBack': 'Welcome back.',
    'home.membershipStatus': 'Membership status',
    'home.membershipRemainingMinutes': 'Membership remaining time (minutes)',
    'home.membershipExpiredMinutes': 'Membership expired, remaining time (minutes)',
    'home.unlimited': 'Unlimited',
    'home.expireAt': 'Expires at: {value}',
    'home.network': 'Network: {value}',
    'home.networkAuto': 'Network: Auto',
    'home.connected': 'VPN connected',
    'home.connecting': 'VPN connecting',
    'home.disconnecting': 'VPN disconnecting',
    'home.disconnected': 'VPN disconnected',
    'home.connectNow': 'Quick Connect',
    'home.disconnectNow': 'Disconnect',
    'home.loggedInAccount': 'Signed-in account',
    'home.guestAccount': 'Guest account',
    'home.lifetime': 'Lifetime',
    'home.active': 'Active',
    'home.expired': 'Expired',
    'home.referral': 'Referral rewards',
    'home.freeMembership': 'Free membership',
    'home.messages': 'Messages',
    'home.support': 'Online support',
    'home.renew': 'Renew membership',
    'home.mobileDownload': 'Mobile app download',
    'home.uploadLogs': 'Upload logs',
    'home.logout': 'Sign out',
    'home.exitApp': 'Exit app',
    'home.version': 'Version: {value}',
    'home.desktopGift': 'Mystery gift kitty~',
    'region.title': 'Change Country / Region',
    'region.selectMode': 'Select mode',
    'region.fastMode': 'Fast mode',
    'region.fastModeDesc': 'Smart split tunneling. Only routes traffic that needs VPN.',
    'region.safeMode': 'Safe mode',
    'region.safeModeDesc': 'Route all network traffic and change your IP address.',
    'region.selectNetwork': 'Select network',
    'region.autoFastest': 'Automatically match the fastest network',
    'region.asia': 'Asia',
    'region.europe': 'Europe',
    'region.africa': 'Africa',
    'region.oceania': 'Oceania',
    'region.northAmerica': 'North America',
    'region.southAmerica': 'South America',
    'referral.title': 'Invite friends, get lifetime membership',
    'referral.detailTitle': 'Referral rewards',
    'referral.detailText': 'After your friend installs LetsVPN and enters your ID ({id}), the referral counts as successful. Every time they get membership, you earn 20% more time. Permanently valid.',
    'referral.rules': 'Detailed rules',
    'referral.share': 'Share with friends',
    'referral.copied': 'Referral code copied',
    'referral.successCount': 'Successful invites',
    'referral.totalEarned': 'Total earned',
    'referral.totalSaved': 'Total saved',
    'referral.empty': 'No referral rewards yet. Invite your friends now!',
    'referral.myRewards': 'My rewards (latest 10 only)',
    'free.title': 'Free membership',
    'free.badge': 'FREE',
    'free.subtitle': 'Come back every day and claim free membership.',
    'free.button': 'Try your luck',
    'free.todayCount': 'Claims today',
    'free.totalHours': 'Total membership claimed',
    'messages.title': 'Messages',
    'messages.geminiTitle': 'Fix Gemini errors with this guide',
    'messages.geminiBody': 'Gemini keeps reporting unsupported regions or random failures? LetsVPN has optimized this flow for a smoother experience.',
    'messages.securityTitle': 'Protect your LetsVPN service from theft',
    'messages.securityBody': 'Please recharge only through official channels and keep your order number safe. It is the only valid proof for support.',
    'settings.autoStartHint': 'Recommended to enable auto start at login.',
    'settings.currentVersion': 'Current version: {value}',
    'settings.copyright': 'Copyright © LetsVPN Team',
    'drawer.loggedIn': 'Signed in',
    'drawer.expired': 'Expired',
    'uploadLogs.title': 'Upload logs',
    'uploadLogs.body': 'Please contact support before uploading logs. Logs are used to analyze issues you encounter while using the app.',
    'toast.loggedOut': 'Signed out',
    'toast.noNodesLoginSync': 'No nodes are available yet. Please sign in and sync your subscription first.',
    'toast.noNodesLoginSyncAlt': 'No nodes are available yet. Please sign in first and sync your subscription.',
    'toast.fastModeRetry': 'Fast mode failed. Switched to safe mode and retried automatically.',
    'toast.connectFailed': 'Connection failed. Please change region or use automatic fastest network.',
    'toast.countrySwitched': 'Switched node: {value}',
    'toast.copyId': 'Copy ID',
    'login.loggedInDesc': 'This account is already signed in. You can close this window and return to the main screen.',
    'login.guestDesc': 'Sign in or register to sync your membership across devices.',
    'login.browserAuth': 'Browser sign-in',
    'login.switchBrowserAuth': 'Use browser sign-in instead',
    'login.titleLogin': 'Sign in',
    'login.titleRegister': 'Register',
    'login.account': 'Account',
    'login.password': 'Password',
    'login.accountHint': '6-20 letters or numbers',
    'login.passwordHint': '6-20 letters or numbers',
    'login.noAccount': 'No account yet?',
    'login.hasAccount': 'Already have an account?',
    'login.registerNow': 'Register now',
    'login.loginNow': 'Sign in now',
    'login.localDevice': 'This device',
    'login.memberLevel': 'Membership',
    'login.remainingTime': 'Remaining time',
    'login.notLoggedIn': 'Not signed in',
    'login.freeMembership': 'Free membership',
    'login.idCopied': 'ID copied',
    'login.copyId': 'Copy ID',
    'login.done': 'Done',
    'auth.loginFailed': 'Sign in failed',
    'auth.registerFailed': 'Registration failed',
    'auth.deviceCodeFailed': 'Failed to get device code',
    'auth.authExpired': 'Authorization expired. Please sign in again.',
    'auth.invalidLoginUrl': 'Invalid sign-in link. Please try again.',
    'auth.openBrowserFailed': 'Unable to open the browser automatically. Please visit: {value}',
    'auth.timeout': 'Authorization timed out. Please try again.',
    'auth.browserFailed': 'Browser authorization failed. Please try again later.',
    'auth.browserFailedDetail': 'Browser authorization failed: {value}',
    'auth.networkError': 'Network error. Please try again later.',
    'auth.accountRequired': 'Please enter your account',
    'auth.accountLength': 'Account length must be 6-20 characters',
    'auth.accountAlnum': 'Account can only contain letters and numbers',
    'auth.passwordRequired': 'Please enter your password',
    'auth.passwordLength': 'Password length must be 6-20 characters',
    'auth.passwordAlnum': 'Password can only contain letters and numbers',
    'connection.missingConfig':
        'The current node configuration is missing. Sync and auto-switch were attempted but still failed. Please sign in again and retry.',
    'desktop.subWindowLoadFailed': 'Window failed to load',
    'desktop.unknownSubWindow': 'Unknown sub-window type: {value}',
    'desktop.loginInitFailed': 'Failed to initialize the sign-in window. Please close it and try again.',
    'routeRules.valueExists': 'This value already exists',
    'jsonEditor.addNewObject': 'Add new object',
    'jsonEditor.configEditor': 'Config Editor',
    'jsonEditor.changeEditor': 'Change editor',
    'jsonEditor.tree': 'Tree',
    'jsonEditor.text': 'Text',
    'jsonEditor.format': 'Format',
    'jsonEditor.results': '{value} results',
    'jsonEditor.expandAll': 'Expand all',
    'jsonEditor.collapseAll': 'Collapse all',
    'jsonEditor.select': 'Select {value}',
    'jsonEditor.typeString': 'String',
    'jsonEditor.typeNumber': 'Number',
    'jsonEditor.typeBoolean': 'Boolean',
    'jsonEditor.typeObject': 'Object',
    'jsonEditor.typeList': 'List',
    'window.countryTitle': 'Choose country',
    'window.loginTitle': 'Sign in',
    'window.expandSidebar': 'Expand sidebar',
    'window.collapseSidebar': 'Collapse sidebar',
  },
  'zh_CN': {
    'splash.initializing': '初始化中...',
    'splash.network': '检查网卡配置...',
    'splash.sdk': '初始化 SDK...',
    'splash.subtitle': '永远能连上的ＶＰＮ',
    'common.back': '返回',
    'common.cancel': '取消',
    'common.upload': '上传',
    'common.insert': '插入',
    'common.append': '追加',
    'common.searchNext': '下一个',
    'common.searchPrevious': '上一个',
    'common.error': '错误',
    'common.copy': '复制',
    'common.idLabel': 'ID: {value}',
    'common.peopleUnit': '人',
    'common.minutesUnit': '分钟',
    'common.hoursUnit': '小时',
    'home.title': '首页',
    'home.welcomeBack': '尊敬的老用户，欢迎回来。',
    'home.membershipStatus': '会员状态',
    'home.membershipRemainingMinutes': '会员剩余时长(分钟)',
    'home.membershipExpiredMinutes': '会员已过期，剩余时长(分钟)',
    'home.unlimited': '不限时',
    'home.expireAt': '到期时间: {value}',
    'home.network': '网络： {value}',
    'home.networkAuto': '网络： 自动',
    'home.connected': 'VPN 已连接',
    'home.connecting': 'VPN 连接中',
    'home.disconnecting': 'VPN 断开中',
    'home.disconnected': 'VPN 已断开连接',
    'home.connectNow': '开启快连',
    'home.disconnectNow': '断开连接',
    'home.loggedInAccount': '已登录账户',
    'home.guestAccount': '未登录账户',
    'home.lifetime': '永久使用',
    'home.active': '会员中',
    'home.expired': '已过期',
    'home.referral': '推荐有奖',
    'home.freeMembership': '免费领会员',
    'home.messages': '消息中心',
    'home.support': '在线客服',
    'home.renew': '续费会员',
    'home.mobileDownload': '手机端下载',
    'home.uploadLogs': '上传日志',
    'home.logout': '退出账号',
    'home.exitApp': '退出程序',
    'home.version': '版本号： {value}',
    'home.desktopGift': '神秘礼物猫咪~',
    'region.title': '变更国家和地区',
    'region.selectMode': '选择模式',
    'region.fastMode': '极速模式',
    'region.fastModeDesc': '智能分流，仅代理需要翻墙的网络流量，不影响本地资源访问。',
    'region.safeMode': '安全模式',
    'region.safeModeDesc': '代理全部网络流量，改变 IP 地址，安全性极强。',
    'region.selectNetwork': '选择网络',
    'region.autoFastest': '自动匹配最快网络',
    'region.asia': '亚洲',
    'region.europe': '欧洲',
    'region.africa': '非洲',
    'region.oceania': '大洋洲',
    'region.northAmerica': '北美洲',
    'region.southAmerica': '南美洲',
    'referral.title': '推荐朋友，领永久会员',
    'referral.detailTitle': '推荐有奖',
    'referral.detailText': '好友安装快连后，填写您的 ID（{id}）即算推荐成功，当其每次获得会员，您均可获取 20% 的时长！永久有效！',
    'referral.rules': '详细规则',
    'referral.share': '推荐给好友',
    'referral.copied': '推荐码已复制',
    'referral.successCount': '成功推荐',
    'referral.totalEarned': '累计获得',
    'referral.totalSaved': '累计白嫖',
    'referral.empty': '暂时还未获得推荐奖励，快去推荐好友吧！',
    'referral.myRewards': '我的奖励（只显示最近 10 条）',
    'free.title': '免费领会员',
    'free.badge': '免费',
    'free.subtitle': '每天都来点一点，免费会员随便领！',
    'free.button': '试试运气',
    'free.todayCount': '今日领取人数',
    'free.totalHours': '累计领取会员',
    'messages.title': '消息中心',
    'messages.geminiTitle': '搞定 Gemini 报错，看这篇就够了',
    'messages.geminiBody': 'Gemini 频繁报错、提示地区不支持？快连已完成专项优化，教你三招彻底告别这些抓狂时刻。',
    'messages.securityTitle': '保护您的快连 VPN 服务不被盗取',
    'messages.securityBody': '请您认准官方渠道充值，并且妥善保管好您的订单号，这是快连 VPN 售后的唯一保障。',
    'settings.autoStartHint': '建议开启开机自动启动。',
    'settings.currentVersion': '当前版本： {value}',
    'settings.copyright': '版权所有 © LetsVPN 团队',
    'drawer.loggedIn': '已登录',
    'drawer.expired': '已过期',
    'uploadLogs.title': '上传日志',
    'uploadLogs.body': '请先和客服沟通后再上传日志，日志用于分析您在 APP 使用中遇到的问题。',
    'toast.loggedOut': '已退出账号',
    'toast.noNodesLoginSync': '暂无可用节点，请先登录并同步订阅。',
    'toast.noNodesLoginSyncAlt': '暂无可用节点，请先登录后同步订阅。',
    'toast.fastModeRetry': '极速模式连接失败，已自动切换到安全模式重试。',
    'toast.connectFailed': '连接失败，请切换国家节点或使用自动匹配最快网络。',
    'toast.countrySwitched': '已切换节点：{value}',
    'toast.copyId': '复制 ID',
    'login.loggedInDesc': '当前账号已登录，您可以关闭窗口返回主界面。',
    'login.guestDesc': '您可以登录或注册一个账户，在不同设备间共享会员时长。',
    'login.browserAuth': '浏览器授权登录',
    'login.switchBrowserAuth': '改用浏览器授权登录',
    'login.titleLogin': '登录账户',
    'login.titleRegister': '注册账户',
    'login.account': '账号',
    'login.password': '密码',
    'login.accountHint': '6-20位字母或数字',
    'login.passwordHint': '6-20位字母或数字',
    'login.noAccount': '没有账号？',
    'login.hasAccount': '已有账号？',
    'login.registerNow': '立即注册',
    'login.loginNow': '立即登录',
    'login.localDevice': '本机设备',
    'login.memberLevel': '会员等级',
    'login.remainingTime': '剩余时间',
    'login.notLoggedIn': '未登录',
    'login.freeMembership': '免费会员',
    'login.idCopied': 'ID 已复制',
    'login.copyId': '复制 ID',
    'login.done': '完成',
    'auth.loginFailed': '登录失败',
    'auth.registerFailed': '注册失败',
    'auth.deviceCodeFailed': '获取设备码失败',
    'auth.authExpired': '授权已过期，请重新登录',
    'auth.invalidLoginUrl': '登录链接无效，请重试',
    'auth.openBrowserFailed': '无法自动打开浏览器，请手动访问：{value}',
    'auth.timeout': '授权超时，请重试',
    'auth.browserFailed': '浏览器授权失败，请稍后重试',
    'auth.browserFailedDetail': '浏览器授权失败：{value}',
    'auth.networkError': '网络错误，请稍后重试',
    'auth.accountRequired': '请输入账号',
    'auth.accountLength': '账号长度必须为6-20位',
    'auth.accountAlnum': '账号只能包含字母和数字',
    'auth.passwordRequired': '请输入密码',
    'auth.passwordLength': '密码长度必须为6-20位',
    'auth.passwordAlnum': '密码只能包含字母和数字',
    'connection.missingConfig': '当前节点配置丢失，已自动尝试同步订阅与切换节点但仍失败，请重新登录后重试。',
    'desktop.subWindowLoadFailed': '窗口加载失败',
    'desktop.unknownSubWindow': '未识别的子窗口类型: {value}',
    'desktop.loginInitFailed': '登录窗口初始化异常，请关闭后重试。',
    'routeRules.valueExists': '该值已存在',
    'jsonEditor.addNewObject': '添加新对象',
    'jsonEditor.configEditor': '配置编辑器',
    'jsonEditor.changeEditor': '切换编辑器',
    'jsonEditor.tree': '树形',
    'jsonEditor.text': '文本',
    'jsonEditor.format': '格式化',
    'jsonEditor.results': '{value} 个结果',
    'jsonEditor.expandAll': '全部展开',
    'jsonEditor.collapseAll': '全部收起',
    'jsonEditor.select': '选择 {value}',
    'jsonEditor.typeString': '字符串',
    'jsonEditor.typeNumber': '数字',
    'jsonEditor.typeBoolean': '布尔值',
    'jsonEditor.typeObject': '对象',
    'jsonEditor.typeList': '列表',
    'window.countryTitle': '选择国家',
    'window.loginTitle': '登录账户',
    'window.expandSidebar': '展开侧边栏',
    'window.collapseSidebar': '收起侧边栏',
  },
  'zh_TW': {
    'splash.initializing': '初始化中...',
    'splash.network': '檢查網卡設定...',
    'splash.sdk': '初始化 SDK...',
    'splash.subtitle': '永遠都能連上的 VPN',
    'common.back': '返回',
    'common.cancel': '取消',
    'common.upload': '上傳',
    'common.insert': '插入',
    'common.append': '追加',
    'common.searchNext': '下一個',
    'common.searchPrevious': '上一個',
    'common.error': '錯誤',
    'common.copy': '複製',
    'common.idLabel': 'ID: {value}',
    'common.peopleUnit': '人',
    'common.minutesUnit': '分鐘',
    'common.hoursUnit': '小時',
    'home.title': '首頁',
    'home.welcomeBack': '尊敬的老用戶，歡迎回來。',
    'home.membershipStatus': '會員狀態',
    'home.membershipRemainingMinutes': '會員剩餘時長(分鐘)',
    'home.membershipExpiredMinutes': '會員已過期，剩餘時長(分鐘)',
    'home.unlimited': '不限時',
    'home.expireAt': '到期時間: {value}',
    'home.network': '網路： {value}',
    'home.networkAuto': '網路： 自動',
    'home.connected': 'VPN 已連線',
    'home.connecting': 'VPN 連線中',
    'home.disconnecting': 'VPN 斷線中',
    'home.disconnected': 'VPN 已中斷連線',
    'home.connectNow': '開啟快連',
    'home.disconnectNow': '中斷連線',
    'home.loggedInAccount': '已登入帳戶',
    'home.guestAccount': '未登入帳戶',
    'home.lifetime': '永久使用',
    'home.active': '會員中',
    'home.expired': '已過期',
    'home.referral': '推薦有獎',
    'home.freeMembership': '免費領會員',
    'home.messages': '訊息中心',
    'home.support': '線上客服',
    'home.renew': '續費會員',
    'home.mobileDownload': '手機端下載',
    'home.uploadLogs': '上傳日誌',
    'home.logout': '退出帳號',
    'home.exitApp': '退出程式',
    'home.version': '版本號： {value}',
    'home.desktopGift': '神祕禮物貓咪~',
    'region.title': '變更國家和地區',
    'region.selectMode': '選擇模式',
    'region.fastMode': '極速模式',
    'region.fastModeDesc': '智慧分流，只代理需要翻牆的網路流量，不影響本地資源存取。',
    'region.safeMode': '安全模式',
    'region.safeModeDesc': '代理全部網路流量，改變 IP 位址，安全性更高。',
    'region.selectNetwork': '選擇網路',
    'region.autoFastest': '自動匹配最快網路',
    'region.asia': '亞洲',
    'region.europe': '歐洲',
    'region.africa': '非洲',
    'region.oceania': '大洋洲',
    'region.northAmerica': '北美洲',
    'region.southAmerica': '南美洲',
    'referral.title': '推薦朋友，領永久會員',
    'referral.detailTitle': '推薦有獎',
    'referral.detailText': '好友安裝快連後，填寫您的 ID（{id}）即算推薦成功，當其每次獲得會員，您都可獲得 20% 的時長！永久有效！',
    'referral.rules': '詳細規則',
    'referral.share': '推薦給好友',
    'referral.copied': '推薦碼已複製',
    'referral.successCount': '成功推薦',
    'referral.totalEarned': '累計獲得',
    'referral.totalSaved': '累計白嫖',
    'referral.empty': '暫時還未獲得推薦獎勵，快去推薦好友吧！',
    'referral.myRewards': '我的獎勵（只顯示最近 10 條）',
    'free.title': '免費領會員',
    'free.badge': '免費',
    'free.subtitle': '每天都來點一點，免費會員隨便領！',
    'free.button': '試試手氣',
    'free.todayCount': '今日領取人數',
    'free.totalHours': '累計領取會員',
    'messages.title': '訊息中心',
    'messages.geminiTitle': '搞定 Gemini 報錯，看這篇就夠了',
    'messages.geminiBody': 'Gemini 經常報錯、提示地區不支援？快連已完成專項優化，教你三招徹底告別這些抓狂時刻。',
    'messages.securityTitle': '保護您的快連 VPN 服務不被盜取',
    'messages.securityBody': '請您認準官方渠道儲值，並妥善保管好您的訂單號，這是快連 VPN 售後的唯一保障。',
    'settings.autoStartHint': '建議開啟開機自動啟動。',
    'settings.currentVersion': '目前版本： {value}',
    'settings.copyright': '版權所有 © LetsVPN 團隊',
    'drawer.loggedIn': '已登入',
    'drawer.expired': '已過期',
    'uploadLogs.title': '上傳日誌',
    'uploadLogs.body': '請先和客服溝通後再上傳日誌，日誌用於分析您在 APP 使用中遇到的問題。',
    'toast.loggedOut': '已退出帳號',
    'toast.noNodesLoginSync': '暫無可用節點，請先登入並同步訂閱。',
    'toast.noNodesLoginSyncAlt': '暫無可用節點，請先登入後同步訂閱。',
    'toast.fastModeRetry': '極速模式連線失敗，已自動切換到安全模式重試。',
    'toast.connectFailed': '連線失敗，請切換國家節點或使用自動匹配最快網路。',
    'toast.countrySwitched': '已切換節點：{value}',
    'toast.copyId': '複製 ID',
    'login.loggedInDesc': '目前帳號已登入，您可以關閉視窗返回主畫面。',
    'login.guestDesc': '您可以登入或註冊一個帳戶，在不同裝置間共享會員時長。',
    'login.browserAuth': '瀏覽器授權登入',
    'login.switchBrowserAuth': '改用瀏覽器授權登入',
    'login.titleLogin': '登入帳戶',
    'login.titleRegister': '註冊帳戶',
    'login.account': '帳號',
    'login.password': '密碼',
    'login.accountHint': '6-20 位字母或數字',
    'login.passwordHint': '6-20 位字母或數字',
    'login.noAccount': '沒有帳號？',
    'login.hasAccount': '已有帳號？',
    'login.registerNow': '立即註冊',
    'login.loginNow': '立即登入',
    'login.localDevice': '本機裝置',
    'login.memberLevel': '會員等級',
    'login.remainingTime': '剩餘時間',
    'login.notLoggedIn': '未登入',
    'login.freeMembership': '免費會員',
    'login.idCopied': 'ID 已複製',
    'login.copyId': '複製 ID',
    'login.done': '完成',
    'auth.loginFailed': '登入失敗',
    'auth.registerFailed': '註冊失敗',
    'auth.deviceCodeFailed': '取得裝置碼失敗',
    'auth.authExpired': '授權已過期，請重新登入',
    'auth.invalidLoginUrl': '登入連結無效，請重試',
    'auth.openBrowserFailed': '無法自動開啟瀏覽器，請手動造訪：{value}',
    'auth.timeout': '授權逾時，請重試',
    'auth.browserFailed': '瀏覽器授權失敗，請稍後重試',
    'auth.browserFailedDetail': '瀏覽器授權失敗：{value}',
    'auth.networkError': '網路錯誤，請稍後重試',
    'auth.accountRequired': '請輸入帳號',
    'auth.accountLength': '帳號長度必須為 6-20 位',
    'auth.accountAlnum': '帳號只能包含字母和數字',
    'auth.passwordRequired': '請輸入密碼',
    'auth.passwordLength': '密碼長度必須為 6-20 位',
    'auth.passwordAlnum': '密碼只能包含字母和數字',
    'connection.missingConfig': '目前節點設定遺失，已自動嘗試同步訂閱與切換節點但仍失敗，請重新登入後再試。',
    'desktop.subWindowLoadFailed': '視窗載入失敗',
    'desktop.unknownSubWindow': '無法識別的子視窗類型: {value}',
    'desktop.loginInitFailed': '登入視窗初始化異常，請關閉後重試。',
    'routeRules.valueExists': '此值已存在',
    'jsonEditor.addNewObject': '新增物件',
    'jsonEditor.configEditor': '設定編輯器',
    'jsonEditor.changeEditor': '切換編輯器',
    'jsonEditor.tree': '樹狀',
    'jsonEditor.text': '文字',
    'jsonEditor.format': '格式化',
    'jsonEditor.results': '{value} 個結果',
    'jsonEditor.expandAll': '全部展開',
    'jsonEditor.collapseAll': '全部收起',
    'jsonEditor.select': '選擇 {value}',
    'jsonEditor.typeString': '字串',
    'jsonEditor.typeNumber': '數字',
    'jsonEditor.typeBoolean': '布林值',
    'jsonEditor.typeObject': '物件',
    'jsonEditor.typeList': '列表',
    'window.countryTitle': '選擇國家',
    'window.loginTitle': '登入帳戶',
    'window.expandSidebar': '展開側邊欄',
    'window.collapseSidebar': '收起側邊欄',
  },
};

const _windowsCountryNames = <String, Map<String, String>>{
  'en': {
    '自动匹配最快网络': 'Automatically match the fastest network',
    '阿根廷': 'Argentina',
    '爱尔兰': 'Ireland',
    '阿联酋': 'United Arab Emirates',
    '澳大利亚': 'Australia',
    '澳门': 'Macau',
    '巴西': 'Brazil',
    '德国': 'Germany',
    '俄罗斯': 'Russia',
    '法国': 'France',
    '菲律宾': 'Philippines',
    '韩国': 'South Korea',
    '荷兰': 'Netherlands',
    '加拿大': 'Canada',
    '马来西亚': 'Malaysia',
    '美国': 'United States',
    '墨西哥': 'Mexico',
    '尼日利亚': 'Nigeria',
    '日本': 'Japan',
    '瑞典': 'Sweden',
    '瑞士': 'Switzerland',
    '泰国': 'Thailand',
    '台湾': 'Taiwan',
    '土耳其': 'Turkey',
    '英国': 'United Kingdom',
    '香港': 'Hong Kong',
    '西班牙': 'Spain',
    '新加坡': 'Singapore',
    '意大利': 'Italy',
    '印度': 'India',
    '印尼': 'Indonesia',
    '越南': 'Vietnam',
    '波兰': 'Poland',
    '挪威': 'Norway',
  },
  'zh_CN': {},
  'zh_TW': {
    '自动匹配最快网络': '自動匹配最快網路',
    '爱尔兰': '愛爾蘭',
    '阿联酋': '阿聯酋',
    '澳门': '澳門',
    '德国': '德國',
    '俄罗斯': '俄羅斯',
    '菲律宾': '菲律賓',
    '韩国': '韓國',
    '马来西亚': '馬來西亞',
    '美国': '美國',
    '墨西哥': '墨西哥',
    '尼日利亚': '奈及利亞',
    '日本': '日本',
    '瑞典': '瑞典',
    '瑞士': '瑞士',
    '台湾': '台灣',
    '英国': '英國',
    '香港': '香港',
    '西班牙': '西班牙',
    '新加坡': '新加坡',
    '意大利': '義大利',
    '印度': '印度',
    '印尼': '印尼',
    '越南': '越南',
    '波兰': '波蘭',
    '挪威': '挪威',
  },
};
